### ISSUE TITLE
Time sync issue for github api

### ISSUE THREAD

**Issue by anujg** [samrocketman/jervis#123]
Hi Sam,

I am experiencing the same issue as https://issues.jenkins-ci.org/browse/JENKINS-47154.

You have listed there that you resolved it by installing ntpdate. I am not able to do that in the current jervis docker container that I have running locally. (I don't see timedatectl installed in my ubuntu container and not able to install it also)
Can you please give the steps that you followed to install ntpdate, or how to update the time in the jervis container?

Thanks
Anuj

**Comment by samrocketman** [comment]
Per the link in that Jenkins issue this is likely resolved upstream https://github.com/hub4j/github-api/pull/595

I haven’t encountered this in a few years.
