### ISSUE TITLE
Matrix build for multiple OS

### ISSUE THREAD

**Issue by akopachevskyy** [samrocketman/jervis#128]
Hi, Sam, sorry I'm using issues as support ticketing
I do have 2 docker agents, ubuntu and centos, both have jdk installed, I do want to bo matrix build and test of the project for both OS's, can you hint me with minimal jervis config to do that?

**Comment by samrocketman** [comment]
Duplicates #107.  There are hacks you can do with toolchains.  The concept of a platform, OS, and toolchain are just that, concepts.  It’s just a way to organized labeled agents in Jenkins.  While #107 aims for full support for matrix building across platform and OS as a concept, there’s not much stopping you from treating a toolchain as an OS instead.

**Comment by samrocketman** [comment]
Refer to:

- https://github.com/samrocketman/jervis/wiki/Matrix-job-support
- https://github.com/samrocketman/jervis/wiki/Specification-for-toolchains-file
- https://github.com/samrocketman/jervis/blob/master/resources/toolchains-ubuntu1604-stable.json

**Comment by akopachevskyy** [comment]
@samrocketman I read all those docs before writing issue, here is approach I've tried to follow and stuck:

First I've updated toolchain file, for java with "java-os", didn't wanted to do "os" to do not mix with existing "os" item:
`   "toolchains": {
        "java": ["env", "jdk", "java-os"],
    },
    "java-os": {
        "friendlyLabel": true,
        "matrix": "advanced",
        "*": [
            "export ${jervis_toolchain_ivalue}"
        ]
    }`

Then I'm created such .jervis.yml entry

`language: java

java-os:
  - centos
  - ubuntu`

But this is not generating different stable for each Jenkins pipeline "parallel" executions, it always create the same set of labels: 

`stable&&docker&&ubuntu1604&&sudo&&"language:java"&&env&&jdk&&java-os`

I probably need some way to generate java-os:ubuntu and java-os:centos so different docker agents with different OS could pick up each parallel tasks.

Can you give me a hint where I'm wrong, please.

**Comment by samrocketman** [comment]
Ah you’re right.  Toolchains isn’t a workaround for that.  I’ll have to add support for it since it’s not possible at the moment.  Follow issue #107 for updates.
