### ISSUE TITLE
Cache artifacts support

### ISSUE THREAD

**Issue by akopachevskyy** [samrocketman/jervis#129]
Hi, it seems caching build artifacts not really working, example:

```
${HOME}/.sbt
${HOME}/.ivy2
/var/cache/apt/archives
```

Jervis will not save this 3 folders in between builds, also I didn't found any mentions of cache handling in the source code, can you please point me on this?

**Comment by samrocketman** [comment]
Jervis is not a 1:1 Travis CI clone.  Rather than caching directories like Travis CI I tend to rely on artifact caching repositories like Sonatype Nexus.  Which, if implemented near the Jenkins server significantly cuts down build time.

I don’t have any plans to implement caching in the Jervis YAML spec at this time.

**Comment by akopachevskyy** [comment]
@samrocketman  just to be 100% sure I understood, from what you saying means caching section here is not been handled? 
https://github.com/samrocketman/jervis/blob/master/.travis.yml

**Comment by samrocketman** [comment]
@akopachevskyy Correct, you'll see that I've grouped my `.travis.yml` file into two sections.

1. `Jenkins Build Options` which contains a mix of Jervis + Jenkins only options as well as some YAML syntax supported by Travis CI.
2. `Travis CI Options Only` which are only options supported by Travis CI (i.e. not Jenkins).  Also note there's comments in the YAML file explaining these two sections as well.

**Comment by samrocketman** [comment]
Closing this as "won't do" for now.  Jenkins has no decent built-in caching mechanism and it's really up to an admin and the surrounding infrastructure an admin maintains to provide this.

That is to say, it is not straightforward to add something like this without requiring a 3rd party service other than Jenkins.
