### ISSUE TITLE
hpi file?

### ISSUE THREAD

**Issue by tparnell8** [samrocketman/jervis#79]
Will there be plans to ship a .hpi file to the jenkins plugin download place? (not sure what the name is, basically [here](http://updates.jenkins-ci.org/download/plugins/))

**Comment by samrocketman** [comment]
As noted on the README and website, this is _not a Jenkins plugin_.  So there's no hpi file to ship.  This is purely a library to be used in Job DSL scripts.  An example Job DSL script is provided [here](https://github.com/samrocketman/jervis/blob/master/jobs/firstjob_dsl.groovy).  Additionally, I provide an [example of `build.gradle`](https://github.com/samrocketman/jervis#gradle) for including the library in the Job DSL scripts repository.

This library is already published to Maven Central and ready to be used in Job DSL scripts.

**Comment by tparnell8** [comment]
Oh I must have missed that in the readme, thanks for clarifying.
